#!/usr/bin/env python3
"""Generate the DSOVS JSON API and the assessment tool's data bundle.

Reads the machine-readable source of truth (``data/controls/*.yaml``) and the
``VERSION`` file, then writes two deterministic artefacts:

* ``dist/dsovs.json``      - the full machine-readable API (consumed by tooling)
* ``assessment/data.js``   - the same payload as ``window.DSOVS_DATA`` so the
                             browser-based self-assessment works with no backend
                             and no fetch (also fine to open from ``file://``).

Both outputs are byte-stable for identical input so CI can assert they are up to
date with ``git diff --exit-code``.
"""

import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTROLS_DIR = REPO / "data" / "controls"
DIST_DIR = REPO / "dist"
ASSESSMENT_DIR = REPO / "assessment"
VERSION_FILE = REPO / "VERSION"

REPO_SLUG = "OWASP/www-project-devsecops-verification-standard"
DOC_BASE = f"https://github.com/{REPO_SLUG}/blob/main/document"

# Semantic SDLC phases in canonical order.
PHASES = [
    "Organisation",
    "Requirements",
    "Design",
    "Code/Build",
    "Test",
    "Release/Deploy",
    "Operate/Monitor",
]
PHASE_ORDER = {name: i for i, name in enumerate(PHASES)}


def read_version() -> str:
    if VERSION_FILE.exists():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "0.0.0"


def load_controls():
    controls = []
    for path in sorted(CONTROLS_DIR.glob("*.yaml")):
        with path.open(encoding="utf-8") as fh:
            controls.append(yaml.safe_load(fh))
    controls.sort(key=lambda c: (PHASE_ORDER.get(c["phase"], 99), c["code"]))
    return controls


def build_control(raw):
    """Project a raw YAML control into the public API shape (stable field order)."""
    control = {
        "id": raw["id"],
        "code": raw["code"],
        "title": raw["title"],
        "phase": raw["phase"],
        "slug": raw["slug"],
        "status": raw["status"],
        "type": raw["type"],
        "summary": raw["summary"].strip(),
        "doc_url": f"{DOC_BASE}/{raw['slug']}.md",
        "levels": [],
    }

    for lvl in raw["levels"]:
        entry = {
            "level": lvl["level"],
            "title": lvl["title"].strip(),
            "description": lvl["description"].strip(),
            "evidence": list(lvl.get("evidence") or []),
        }
        diagram = lvl.get("diagram")
        if diagram:
            entry["diagram"] = diagram.strip()
        control["levels"].append(entry)

    if raw.get("tools"):
        control["tools"] = []
        for tool in raw["tools"]:
            out = {
                "name": tool["name"],
                "url": tool["url"],
                "description": tool["description"].strip(),
            }
            if tool.get("integrations"):
                out["integrations"] = [
                    {
                        "platform": ig["platform"],
                        "label": ig.get("label"),
                        "link": ig.get("link"),
                        "code": ig["code"].rstrip("\n"),
                    }
                    for ig in tool["integrations"]
                ]
            control["tools"].append(out)

    if raw.get("further_reading"):
        control["further_reading"] = [
            {"url": fr["url"], "note": fr.get("note", "")}
            for fr in raw["further_reading"]
        ]

    if raw.get("mappings"):
        mappings = {k: list(v) for k, v in raw["mappings"].items() if v}
        if mappings:
            control["mappings"] = mappings

    if raw.get("credits"):
        control["credits"] = [
            {"name": c["name"], "url": c.get("url")} for c in raw["credits"]
        ]

    return control


def build_payload():
    controls = [build_control(c) for c in load_controls()]
    present_phases = [p for p in PHASES if any(c["phase"] == p for c in controls)]
    return {
        "standard": "OWASP DevSecOps Verification Standard",
        "abbreviation": "DSOVS",
        "version": read_version(),
        "source": "data/controls/*.yaml",
        "generator": "scripts/generate_json.py",
        "phases": present_phases,
        "control_count": len(controls),
        "controls": controls,
    }


def main():
    if not CONTROLS_DIR.exists():
        print(f"error: {CONTROLS_DIR} not found", file=sys.stderr)
        return 1

    payload = build_payload()
    pretty = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    ASSESSMENT_DIR.mkdir(parents=True, exist_ok=True)

    (DIST_DIR / "dsovs.json").write_text(pretty, encoding="utf-8")

    banner = (
        "// Generated by scripts/generate_json.py - do not edit by hand.\n"
        "// Source of truth: data/controls/*.yaml\n"
    )
    data_js = banner + "window.DSOVS_DATA = " + pretty.rstrip("\n") + ";\n"
    (ASSESSMENT_DIR / "data.js").write_text(data_js, encoding="utf-8")

    print(
        f"Wrote dist/dsovs.json and assessment/data.js "
        f"({payload['control_count']} controls, v{payload['version']})."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
